install.packages("BiocManager")
install.packages("tidyverse")
install.packages('Seurat')
install.packages("reshape2")
install.packages("pheatmap")
install.packages("RColorBrewer")
install.packages("viridis")
install.packages("gggibbous")
install.packages("tidytext")
install.packages("hrbrthemes")
install.packages("ggsci")
install.packages("igraph")
install.packages("gprofiler2")
install.packages("plotly")
install.packages("devtools")

if (!requireNamespace("readxl", quietly = TRUE)) 
  install.packages("readxl")
if (!requireNamespace("ggplot2", quietly = TRUE)) 
  install.packages("ggplot2")
if (!requireNamespace("dplyr", quietly = TRUE)) 
  install.packages("dplyr")
if (!requireNamespace("tidyr", quietly = TRUE)) 
  install.packages("tidyr")
if (!requireNamespace("readr", quietly = TRUE)) 
  install.packages("readr")
if (!requireNamespace("tibble", quietly = TRUE)) 
  install.packages("tibble")

BiocManager::install("progeny")
BiocManager::install("dorothea")
#BiocManager::install("CARNIVAL")
devtools::install_github("saezlab/CARNIVAL@v1.3")
BiocManager::install("biomaRt")
BiocManager::install("org.Hs.eg.db")
BiocManager::install("RCy3")
BiocManager::install("MAST")
BiocManager::install("OmnipathR")
BiocManager::install("fgsea")
BiocManager::install("piano")
BiocManager::install("clusterProfiler")
BiocManager::install("ReactomePA", update = FALSE, ask = FALSE)
